### ISSUE TITLE
Be part of Hacktoberfest!

### ISSUE THREAD

**Issue by joelibaceta** [joelibaceta/hacktoberfest-2019#2]
1. Fork this repo
2. Add your name to contributors.md
3. Add a simple line in survey.md with your responses according to next structure

```
| Main Programming Language | Operating System | IDE or Editor | Country | Age | 
```

4. make a PR, and mention this issue  happy coding!

**Comment by sparshag21** [comment]
Hey! I see no contributors.md
Should I make one?

**Comment by joelibaceta** [comment]
@sparshag21 I'm still working on this repo :c

**Comment by joelibaceta** [comment]
@sparshag21 ok, the contributors.md already exists

**Comment by BPearlstine** [comment]
@joelibaceta 

I noticed that my PR as well as a number of others are all failing the Travis builds. Do you have an idea of what is going on there? Is it an issue with attempting to merge upstream?

**Comment by grendach** [comment]
Add myself to survey #51
